name: Deploy Website to Azure Blob Storage

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest