name: Destroy Azure Website Infrastructure

on:
  push:
    branches:
      - destroy

permissions:
  id-token: write
  contents: read

jobs:

  destroy:

    name: Terraform Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          terraform destroy \
            -auto-approve \
            -var="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}"

      - name: Destroy Complete
        run: |
          echo "Azure infrastructure destroyed successfully." 
          